# Generated by Django 4.0.3 on 2022-04-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjHandler',
            fields=[
                ('title', models.CharField(blank=True, max_length=100)),
                ('video_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('publish_date', models.DateTimeField()),
                ('views', models.BigIntegerField(blank=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
