# Generated by Django 4.0.3 on 2022-04-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objhandler',
            name='id',
            field=models.BigAutoField(auto_created=True, default=45, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objhandler',
            name='video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
