# Generated by Django 4.0.3 on 2022-04-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_objhandler_id_alter_objhandler_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='objhandler',
            name='channel_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
