# Generated by Django 4.0.3 on 2022-04-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_objhandler_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='objhandler',
            name='length',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objhandler',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
