# Generated by Django 4.0.3 on 2022-04-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_objhandler_length_objhandler_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_videoId', models.CharField(blank=True, max_length=100)),
                ('channel_name', models.CharField(blank=True, max_length=100)),
                ('channel_image', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
