# Generated by Django 4.0.3 on 2022-04-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_channel_videoid_popularchannel_channel_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularchannel',
            name='channel_category',
            field=models.CharField(blank=True, choices=[('Popular Song', 'Song'), ('Popular Video', 'Video')], max_length=100),
        ),
    ]
