# Generated by Django 4.0.3 on 2022-05-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_popularchannel_channel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='objhandler',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='popularchannel',
            name='channel_category',
            field=models.CharField(choices=[('Popular Song', 'Song'), ('Popular Video', 'Video')], max_length=100),
        ),
        migrations.AlterField(
            model_name='popularchannel',
            name='channel_image',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='popularchannel',
            name='channel_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
